### ISSUE TITLE
Any way to exclude node_modules?

### ISSUE THREAD

**Issue by petrgazarov** [Urthen/case-sensitive-paths-webpack-plugin#24]
Hi there! Thanks for the library.

I'm getting an error from a third-party package that I installed in `node_modules`.

```
ERROR in ./node_modules/react-codemirror/lib/Codemirror.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/petrgazarov/workspace/clause/packages/clause-hub/node_modules/react-codemirror/src/codemirror.js` does not match the corresponding path on disk `Codemirror.js`.
 @ ./node_modules/react-codemirror/lib/Codemirror.js 38:42-63
 @ ./src/components/TemplateForm/Form.js
 @ ./src/components/TemplateForm/index.js
 @ ./src/containers/Dashboard/index.js
 @ ./src/routes/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8888 ./src/main.js
```

**Comment by Urthen** [comment]
Hey @petrgazarov - There's not any possibility for exclusions right now, by design. Any exclusion, even for third-party code, effectively could mean that your whole build could fail on case-sensitive systems and therefore bypass the whole point of this plugin.

It looks like there is a [fork of react-codemirror](https://github.com/scniro/react-codemirror2) available which resolves this particular issue, which might help you move forward.

If you need to use react-codemirror for some reason, unfortunately the best I can offer you is to disable this plugin until react-codemirror [merges the PR](https://github.com/JedWatson/react-codemirror/pull/124) to fix the case-sensitivity issue, though it's been open since July so not sure when/if it'll ever be looked at.

**Comment by petrgazarov** [comment]
Hey @Urthen, thanks for your answer! It makes perfect sense why you don't want to be able to "exclude" directories. `react-codemirror2` project indeed solves the casing problem. 👍
