### ISSUE TITLE
I want to make it case-insensetive

### ISSUE THREAD

**Issue by RamadanM** [Urthen/case-sensitive-paths-webpack-plugin#25]
Hey all,
I am working with a team all of them use windows machine but I use fedora , when I start to clone the project everything is working well in their machines but after i have run npm start there is many errors  like this

> ERROR in ./router.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ./features/patientGrid/index in /myRepoInFedoraMachine 
Do you have any suggestions  ?

**Comment by Urthen** [comment]
Hi @RamadanM,

Are you actually using this plugin currently, or trying to add it? The point of this plugin is to expose improper casing and prevent these kinds of errors.

**Comment by Urthen** [comment]
Hello again, without further information I can't help you.

**Comment by RamadanM** [comment]
Hi @Urthen , I was using this plugin , I will try to rewrite the problem in a good way , as you know that Linux file system is case sensitive and windows is case insensitive , my new team working on a react js project ,but all of them have windows machines , for me I don't prefer windows , I want to work on a Linux machine , after I have cloned the git repo for React JS project , I can't run it because the deference in filenames and paths , if you don't understand my issue I will try to explain it in a different way .

**Comment by Urthen** [comment]
If everyone is running a project with this plugin properly installed and working, the teammates using Windows should see errors from this plugin when they attempt to run code with improper filenames. If you are seeing `Module not found` errors on your Linux (case-sensitive) machine, it most likely means the code is incorrect, the problem this plugin is meant to clearly identify (and help prevent), which is why I am confused.

Does the file ` ./features/patientGrid/index` exist like that, exactly as cased, in the repository? If it exists but isn't cased the same, it seems like this plugin isn't getting used (or at least used correctly).

**Comment by Urthen** [comment]
Closing (again) due to inactivity.
